FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend ./frontend
COPY utils ./utils
COPY config ./config

EXPOSE 8501
CMD ["python", "frontend/app.py"]